# Database connection.
# When Slacker is executed, it will attempt to connect to this database.

# Replace the following with your connection information.
# Note that at this point Slacker only works with SQL Server authentication.
server: mssql
database: WideWorldImportersTest
user: sa
password: Yukon900
driver: tiny_tds
port: 1433
console_enabled: false
