# Database connection.
# When Slacker is executed, it will attempt to connect to this database.

# Replace the following with your connection information.
# Note that at this point Slacker only works with SQL Server authentication.
server: kubernetes
database: WideWorldImportersTest
user: sa
password: Yukon900
driver: tiny_tds
port: 32188
console_enabled: true
